### ISSUE TITLE
Nvidia Deepstream SDK module runtime backoff with Exit Code 255

### ISSUE THREAD

**Issue by leela-uppuluri** [Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano#12]
I was trying to run Nvidia Deepstream SDK example. But when I was trying to run Deepstream to output the inferred videos to an RTSP video stream and visualize this RTSP stream with VLC, I am running into `Exit Code 255` error and the runtime status shows `backoff`. I was trying to run same steps that was mentioned in the ReadMe file but don't understand why the Deepstream SDK module doesn't work.

Here's the snapshot of my deployed Azure IoT Edge resources,

![img-1](https://user-images.githubusercontent.com/43678538/77504463-6d541780-6e2e-11ea-8154-f218249c1953.JPG)

**Comment by Zvikas1** [comment]
Hi ,

I am also having the same problem , after deploying Deepstream sdk status goes to "backoff" then "failed" , i will be glad to help

**Comment by leela-uppuluri** [comment]
Hi Vikas,

Thanks for your response, I tried to check the logs of Deepstream SDK module to see why it is failing and found it is looking for some file I think config file but for some reason it shows "No such file or directory". Attached snapshot of the logs,

![Screenshot from 2020-03-30 00-34-30](https://user-images.githubusercontent.com/43678538/78050052-67d06300-7341-11ea-8d5e-70ad30467679.png)

**Comment by leela-uppuluri** [comment]
@Zvikas1 Do you have any suggestions on the above comment?

**Comment by Zvikas1** [comment]
@leela-uppuluri , 

I was trying to understand , have you succeeded in deploying the SDKDeepstream Module ? Cause mine are failing after 30 sec . Are you running in your snapshot the logs of the test5 app example from the nano ? Which logs are you looking at ? Can you elaborate please?

**Comment by leela-uppuluri** [comment]
@Zvikas1 I could able to successfully deploy Deepstream SDK module but I see the module is going under "backoff" status after few mins it is deployed. I tried running this module on bare metal IoT Edge device server attached with data center GPU (Nvidia T4). I am looking at the logs on visual studio code using the option "Start Monitoring Built-in Endpoint" on IoT Hub and I am checking this logs right after the SDK module was deployed.

**Comment by leela-uppuluri** [comment]
@Zvikas1 Does the above comment helps?

**Comment by ebertrams** [comment]
Sorry for the delay. Correct this issue was because of a version mismatch. This sample has been updated with jetpack 4.5 and DeepStream 5.1, so it should go away with when using this version.
