### ISSUE TITLE
Format of deployment.template.json for RTSP and 8 Video stream

### ISSUE THREAD

**Issue by EHUbels** [Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano#13]
I'm a novice to Azure Vision AI, have been able to get the Jetson NVIDIA and the initial example working. I'm trying to get the RTSP as well as the 8 video's sample to work. To do so the deployment.template.json file needs to be edited. That works fine, till you get to the adding and changing some of the entries, the instruction is getting vague, were do I add what, sometimes there is already and entry with the same name, do I add or replace.  Would it be possible to get complete correct examples of the deployment.template.json files for both RTSP and 8 video's example. 

Thanks in advance.

**Comment by ebertrams** [comment]
This [deployment.template.json](https://github.com/Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano/blob/master/DeepstreamOnIoTEdge/deployment.template.json) file has all the options from this tutorial. This [deepstream config file](https://github.com/Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano/blob/master/DeepstreamOnIoTEdge/modules/NVIDIADeepStreamSDK/configs/test5_config_file_src_infer_aziotedge_nano_8sources.txt) is the one to use for the 8 video examples and also has RTSP turned on.
