### ISSUE TITLE
Stability / Failed NVIDIADeepstreamSDK Edge Module

### ISSUE THREAD

**Issue by EHUbels** [Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano#14]
While following the example and get it to work initially it turn out that after a while the NVIDIADeepsteamSDK first get into a 'backoff' state and after a number of restarts up to a max of 20 it get's into a 'failed' status. What could be the reason. I've build completely as the demo says and checked for all version and pieces of code to be correct.

**Comment by NeverOddOrEven** [comment]
NVIDIA released JetPack 4.4 in April. Make sure you are using JetPack 4.3. (I also ran into this issue and resolved it by flashing JetPack 4.3 onto my MicroSD card. You want [release 32.3.1](https://developer.download.nvidia.com/embedded/L4T/r32-3-1_Release_v1.0/Jetson-Nano-SDCard-Image/nv-jetson-nano-sd-card-image-r32.3.1.zip)

**Comment by ebertrams** [comment]
Sorry for the delay. This sample has been updated with jetpack 4.5 and DeepStream 5.1.
