### ISSUE TITLE
is the project currently supported/ maintained?

### ISSUE THREAD

**Issue by AndreV84** [Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano#19]
will it work with Jetson OS from the most recent 4.5.1 Jetpack release?

**Comment by ebreton** [comment]
Also interested in the answer :)

**Comment by ebertrams** [comment]
Sorry for the delay @AndreV84 , @ebreton . Finally updated to support 4.5.1 jetpak and DeepStream 5.1. The custom Vision custom YOLO plugin source code has also been released as part of this update.

**Comment by AndreV84** [comment]
@ebertrams Thank you for the update.
However could you confirm if the following deployment json file is correct as it is little bit ambigious which exac tly lines of the file to update but like that
```
{
  "$schema-template": "2.0.0",
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {}
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.1",
              "createOptions": {}
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.1",
              "createOptions": {
                "HostConfig": {
                  "PortBindings": {
                    "5671/tcp": [
                      {
                        "HostPort": "5671"
                      }
                    ],
                    "8883/tcp": [
                      {
                        "HostPort": "8883"
                      }
                    ],
                    "443/tcp": [
                      {
                        "HostPort": "443"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "modules": {
          "NVIDIADeepStreamSDK": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "marketplace.azurecr.io/nvidia/deepstream51-l4t:latest",
              "createOptions": {
                "HostConfig": {
                  "runtime": "nvidia",
                  "ExposedPorts":{
                    "8554/tcp": {}
                },
                "PortBindings": {
                  "8554/tcp": [
                      {
                      "HostPort": "8554"
                      }
                  ]
              },
              
                
                   "Binds": ["/var/deepstream/custom_configs/:/opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/deepstream-test5/custom_configs/"]
                },
                "WorkingDir": "/opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/deepstream-test5/custom_configs/",
                "Entrypoint":["/usr/bin/deepstream-test5-app","-c","test5_config_file_src_infer_azure_iotedge_edited.txt"]
              }
            }
          }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {
          "DeepstreamToIoTHub": "FROM /messages/modules/NVIDIADeepStreamSDK/outputs/* INTO $upstream"
        },
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    }
  }
}
```

**Comment by AndreV84** [comment]
otherwise coudl you share the deployment json file please, that has edits already, please?

**Comment by emmanuel-bv** [comment]
Hi @AndreV84 yes this is the correct deployment file for Deepstream 5.1. The important part to update is the NVIDIADeepStreamSDK section with an updated image, updated bind paths, updated working dir and updated entrypoint. Rest has not really changed.

**Comment by AndreV84** [comment]
@ebertrams could you share a tested deployment json file that has incorporated multiple changes mentinoed in the readme, please?
Including the folllowing, please?
```
Mount your updated config file in the Deepstream module by adding its createOptions in the deployment.template.json file from your development's machine:

Add the following to your Deepstream createOptions:
"HostConfig":{
    "Binds": ["/var/deepstream/custom_configs/:/opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/deepstream-test5/custom_configs/"]
    }
Edit your Deepstream application working directory and entrypoint to use this updated config file via Deepstream createOptions:
"WorkingDir": "/opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/deepstream-test5/custom_configs/"
"Entrypoint":["/usr/bin/deepstream-test5-app","-c","test5_config_file_src_infer_azure_iotedge_edited.txt"]
Open the RTSP port of DeepStream module so that you can visualize this feed from another device:

Add the following to your Deepstream createOptions, at the root:
"ExposedPorts":{
    "8554/tcp": {}
}
Add the following to your Deepstream createOptions, in the HostConfig node:
"PortBindings": {
    "8554/tcp": [
        {
        "HostPort": "8554"
        }
    ]
}

**Comment by AndreV84** [comment]
as otherwise without exact line numbers also without a complete updated json file that has these lines, as a reference it is like high chance to add edits with causing loss of integrity

**Comment by AndreV84** [comment]
@ebreton could you maybe also share some insights how to incorporate into the test5 example sending of a serial data from jetson board, e.g. from /dev/ttyACM0 so it would go to the Azure IoT broker/messages?

**Comment by ebreton** [comment]
Our current implementation has an independent process which reads the GPS coordinates (20 time per seconds). 

It has 2 responsabilities:
1. send all coordinates to another process that selects the image to run the inference on (aka broker). Hence all analyzed images get geo-located. The frequence could be up to 6 times per seconds
2. send an "heartbeat" to Azure to track the location of the device. The frequence is once every 20 seconds or so

The communication between the GPS reader and the broker is made thanks to ZMQ
The communication between the GPS and Azure is made thanks to Azure IoT

**Comment by AndreV84** [comment]
@ebertrams 
Could you share an example of a modified json file, please? The example that has all modifications directed b the readme file of the repository, please?
E.g. I am having hard times trying to find exactly which line number to paste incorporate this direction from the readme file as there are many entries named "Host Config" so which line needs to be selected before pasting the add thing?
```
Mount your updated config file in the Deepstream module by adding its createOptions in the deployment.template.json file from your development's machine:

Add the following to your Deepstream createOptions:
```
then such line needs to be added, but to where at the file exactly to add it? as a new line or as a substitute line?
```
"HostConfig":{
    "Binds": ["/var/deepstream/custom_configs/:/opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/deepstream-test5/custom_configs/"]
    }
```
It might be required to avoid probably ambigious gaps that would probably cause loss of integrity after doing manual changes to the file using the recomendations in the github readme file without knowing exactly line number of where to add or modify to incorporate the directions. The complication is that there is no specific line numbers or a reference deployment json file that has these edits already to check with. , but just generic directions like to add such and such  modificationafter such and such WORD , given the WORD is present in plural, results in ambigious situation which could result in use of errorneous place[line] of the file to add edits. That will likely result in loss of integrity so the whole thing might broke, in my opinion
@ebertrams  ?
for example after applying few instruction it looks like 
```
"modules": {
          "NVIDIADeepStreamSDK": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "marketplace.azurecr.io/nvidia/deepstream51-l4t:latest",
              "createOptions": {
                "HostConfig": {
                  "runtime": "nvidia"
                },
                "WorkingDir": "/opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/deepstream-test5/configs",
                "Entrypoint": [
                  "/usr/bin/deepstream-test5-app",
                  "-c",
                  "test5_config_file_src_infer_azure_iotedge.txt",
                  "-p",
                  "1",
                  "-m",
                  "1"
                ]
              }
```
for lines 55-75
but I suspect it won't run

**Comment by AndreV84** [comment]
the problem is that it deploys to the device also it says successfully
However, it doesn't seem to generate 8554/ds-test output so it is not possible to monitor if it actually worked
Moreover, the subscription to device events doesn't show any informative information but 
```
[IoTHubMonitor] Start monitoring message arrived in built-in endpoint for device [nvidia-jetson] ...
[IoTHubMonitor] Created partition receiver [0] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [1] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [2] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [3] for consumerGroup [$Default]
