### ISSUE TITLE
Deepstream 5.1 can't work on a NVIDIA Jetson Nano 4.5

### ISSUE THREAD

**Issue by linsteveny** [Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano#22]
Hello, 
  I installed successfully JetPack 4.5 at my Nano. 
  And I deploy Deepstream 5.1 from the Azure Marketplace, still has error as follows:

  ** ERROR: <create_osd_bin:58>: Failed to create 'nvosd0'
  ** ERROR: <create_osd_bin:100>: create_osd_bin failed
  ** ERROR: <create_processing_instance:802>: create_processing_instance failed
  ** ERROR: <create_pipeline:1294>: create_pipeline failed
  ** ERROR: <main:1419>: Failed to create pipeline
  Quitting
  App run failed

  What’s the problem?

**Comment by hulloanson** [comment]
How did you solve this problem?

I now have the same error on AGX Xavier
