### ISSUE TITLE
Sending video clips with detection messages

### ISSUE THREAD

**Issue by js1972** [Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano#5]
Thanks for this tutorial. I’m wondering how you would go about sending video clips to azure when a detection is made and not just a text-based message?
For example in a security scenario if you were alerted to detections from your edge device you would then want to be able to watch the video for that detection??

**Comment by ebertrams** [comment]
Hi @js1972 , we are working on enabling this scenario. I don't have a solution to share publicly yet but feel free to email me at ebertra@microsoft.com if you have some customer engagmenets and want to deep dive on our current thoughts to implement this.
I m closing this for now as it was mostly a question and we ll make sure to update this repo once we have a solution. Thank you!
