### ISSUE TITLE
Customized test app 

### ISSUE THREAD

**Issue by amarrmb** [Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano#6]
Thanks a lot for this tutorial! How can i have my own test app part (instead of the test5) app? Are the steps to build a deepstream container open or is there some secret sauce for which we will have to use the container as is?

**Comment by ebertrams** [comment]
Hi @amarrmb , you can build your own deepstream application using the plugins that you need. To learn more about how to do this, you can refer to this question: https://github.com/Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano#when-should-you-consider-building-your-own-deepstream-application-vs-reconfiguring-an-existing-one
